### ISSUE TITLE
Error on RegisterExtension

### ISSUE THREAD

**Issue by tolidano** [Andrew-Dickinson/nyct-gtfs#4]
During import I am seeing this: 
```
[ERROR] AttributeError: type object 'FeedHeader' has no attribute 'RegisterExtension'
Traceback (most recent call last):
  File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/merge.py", line 20, in <module>
    from parsers.mta_trips import gtfs_files, mta_trips
  File "/var/task/parsers/mta_trips.py", line 4, in <module>
    from nyct_gtfs import NYCTFeed
  File "/var/task/nyct_gtfs/__init__.py", line 1, in <module>
    from nyct_gtfs.feed import NYCTFeed
  File "/var/task/nyct_gtfs/feed.py", line 7, in <module>
    from nyct_gtfs.compiled_gtfs import nyct_subway_pb2, gtfs_realtime_pb2
  File "/var/task/nyct_gtfs/compiled_gtfs/nyct_subway_pb2.py", line 62, in <module>
    gtfs__realtime__pb2.FeedHeader.RegisterExtension(nyct_feed_header)
```

**Comment by tolidano** [comment]
My specific versions of things: 
```
__pycache__                           certifi                               httpcore                              merge.py                              s3transfer
anyio                                 certifi-2024.2.2.dist-info            httpcore-1.0.5.dist-info              nyct_gtfs                             s3transfer-0.10.1.dist-info
anyio-4.3.0.dist-info                 charset_normalizer                    httpx                                 nyct_gtfs-1.3.2.dist-info             six-1.16.0.dist-info
bin                                   charset_normalizer-3.3.2.dist-info    httpx-0.27.0.dist-info                parsers                               six.py
boto3                                 dateutil                              idna                                  protobuf-5.26.1.dist-info             sniffio
boto3-1.34.79.dist-info               google                                idna-3.6.dist-info                    python_dateutil-2.9.0.post0.dist-info sniffio-1.3.1.dist-info
botocore                              h11                                   jmespath                              requests                              urllib3
botocore-1.34.79.dist-info            h11-0.14.0.dist-info                  jmespath-1.0.1.dist-info              requests-2.31.0.dist-info             urllib3-2.2.1.dist-info
```

**Comment by tolidano** [comment]
I think it requires regenerating the protos? But it's not clear. If it is that, dropping instructions for how to do that, I would be happy to do it and put up a PR.

**Comment by tolidano** [comment]
This other project has the "extend" block which seems like where this would come into play: https://github.com/jonthornton/MTAPI/blob/master/mtaproto/nyct-subway.proto#L32 But this is 5 years ago.

**Comment by tolidano** [comment]
One potential script to generate this: 
```

set -euo pipefail

curl https://api.mta.info/nyct-subway.proto.txt -o nyct-subway.proto
curl https://developers.google.com/static/transit/gtfs-realtime/gtfs-realtime.proto -o gtfs-realtime.proto

protoc -I=. --python_out=. --mypy_out=. nyct-subway.proto gtfs-realtime.proto
```
Requires protoc, which is available in brew on my Mac via `brew install protobuf` and then you need protoc-gen-mypy which you can get with `pipx install mypy-protobuf`

Even after running this, I can see a diff in the files vs what is in compiled but it's not clear what happened or when.

**Comment by tolidano** [comment]
When running 1.3.0 locally, it appears to be fine:
```
> v /Users/shawn/.pyenv/versions/3.11.3/lib/python3.11/site-packages/nyct_gtfs
nyct_gtfs/                  nyct_gtfs-1.3.0.dist-info/
```
Will check pinning to 1.3.0 and 1.3.1 to see.

**Comment by tolidano** [comment]
So locally, I have an M2 Max MacBook Pro and when I use 1.3.0, it works:
```
> v package/nyct_gtfs
nyct_gtfs/                  nyct_gtfs-1.3.0.dist-info/
```
But on lambda it fails.

**Comment by tolidano** [comment]
I believe I have narrowed it down to this: 
`if _descriptor._USE_C_DESCRIPTORS == False:`
This is True locally, so it does not attempt to do this.

But on Lambda it's false, so it does, and it says it does not exist.

**Comment by tolidano** [comment]
The logic in google/protobuf/descriptor.py: 
```
_USE_C_DESCRIPTORS = False
 if api_implementation.Type() != 'python':
   # pylint: disable=protected-access
   _message = api_implementation._c_module
   # TODO: Remove this import after fix api_implementation
   if _message is None:
     from google.protobuf.pyext import _message
   _USE_C_DESCRIPTORS = True
```

**Comment by tolidano** [comment]
Looks like I might be able to force it by defining `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` as `cpp` in the lambda env.

EDIT: I tried all 3 values, cpp (failed immediately), upb (failed the same way as above) and python (same as upb). No luck there.

**Comment by tolidano** [comment]
Maybe relevant: https://github.com/protocolbuffers/protobuf/issues/13743

**Comment by tolidano** [comment]
Got it - the answer is that because RegisterExtension was deprecated, when they dropped the 5 series of protobuf last month, they removed it. https://pypi.org/project/protobuf/#history I forced my requirements to pull 4.25.3 and it worked. This may be required on your project as well, unless you have a more suitable solution.

**Comment by Andrew-Dickinson** [comment]
Would love a PR to pin that in `setup.py` otherwise I will try to remember to do that myself this week
